project:
  type: website
output-dir: _site
website:
  title: tutorial_dataviz
  navbar:
    left:
    - href: index.qmd
      text: Home
    - lecture1.qmd
    - lecture1_2.qmd
format:
  html:
    theme: cosmo
    css:
    - _extensions/include/webex.css
    include-after-body:
    - _extensions/include/webex.js
    embed-resources: true
    toc: true
execute:
  echo: false
  warning: false
  message: false
bibliography: references.bib
fig-cap-location: top
editor: visual
